package model;

import java.time.*;
import java.util.*;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;

@Entity(name = "semesters")
public class Semester {

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    @Column(name = "semester_id")
    private int semesterId;

    @Column(length = 16)
    @NotNull
    private String title;

    @Column(name = "start_date")
    @NotNull
    private LocalDate startDate;

    /*
     * Bidirectional OneToMany Semester[Parent] -> Section[Child]
     * A semester has many sections
     */
    @OneToMany(mappedBy = "semester")
    private List<Section> sections;

    public Semester() {

    }

    /*
     * A semester must have a title and startDate to initialize
     * Semester ID is autogenerated
     */
    public Semester(@NotNull String title, @NotNull LocalDate startDate) {
        this.title = title;
        this.startDate = startDate;
    }

    public void addSection(Section s) {
        this.sections.add(s);
        s.setSemester(this);
    }

    @Override
    public String toString() {
        return "Semester [sections=" + sections + ", semesterId=" + semesterId + ", startDate=" + startDate + ", title="
                + title + "]";
    }

    public int getSemesterId() {
        return semesterId;
    }

    /*
     * Semester ID is a primary key therefore no setters
     */
    // public void setSemesterId(int semesterId) {
    // this.semesterId = semesterId;
    // }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public List<Section> getSections() {
        return sections;
    }

    public void setSections(List<Section> sections) {
        this.sections = sections;
    }

}
